# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "Files/", "/Vagrant"
  config.vm.define "Carimali-IoT" do |stat| end
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network", ip: "192.168.0.10", bridge: "en1: Wi-Fi (AirPort)"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.ssh.forward_agent = true

  config.vm.provision "shell" do |sh|
    sh.path ="Scripts/influx.sh"
  end 

  config.vm.provision "shell" do |sh|
    sh.path ="Scripts/grafana.sh"
  end 

  config.vm.provision "shell" do |sh|
    sh.path ="Scripts/telegraf.sh"
  end 

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    sudo service grafana-server restart
    sudo service telegraf restart
    sudo service influxdb restart
    SHELL
  end

